// Star targets tracing only the Abu Dhabi skyline silhouette: tower
// crowns, spires and the steps between them. The waterline is left open
// under the city and drawn at runtime from each end out to the viewport.
// Same plate frame as skylineGrains.ts. Records are uint16 x, uint16 y and
// a uint8 random size, ordered so any prefix spans the whole outline.
// Generated by tmp-skyline/build_outline.py.

import type { SkylineGrains } from './skylineGrains'

/** Plate x where the profile meets the waterline on the left and right. */
export const OUTLINE_LEFT = 0.026367
export const OUTLINE_RIGHT = 0.972656
export const OUTLINE_HORIZON_DIM = 0.7

/** Dot radius in plate px for a size in 0–1; dots are spaced edge to edge by this. */
export function outlineRadius(b: number) {
  return 0.4 + 1.6 * b ** 1.8
}

/** Clear space between neighbouring dots, plate px, before and after jitter. */
export const OUTLINE_GAP_MIN = 0.45
export const OUTLINE_GAP_JITTER = 0.9

const PACK = [
  'BsCWmSG+f2xwv2ewaSzZKMCAXXKTf1wlkhpAf2td1Rxzd7aCPxggjUyAeCLMqD9fZh4UkXWVIce/c8DtdwA82w84GWzBsp5Jei6vIsCHYa3jQnqh/I9/UGNA',
  'X0Bma1Sv/2a9qw7AjrMgxL9WH41rC1JZnTUAjN2Ymn9Z/qAgwIs/OtjaYKtujn8oHqxUQG60nKw/VXetGECVUxDKenajWIFWQHIkQEB8C2OgP1yS+ieAhevF',
  '9VR7E3qPv3Tk5WTAhDyvtRdiS7MI6JaZR8MiZdZtacBieh0tVIdNd5VPSzDtH0CBACDWUWHj9Io/G1EgUQB18nOp8lXuJRdAg+C7yT9mdkd7njZe4D1AbrX4',
  'n790SFElAIYlc+x/emDYj39gjMZjQG9jgrD/cM7AEDJ/GrHHP2apNHZXUGSzNUB6vDWav2sVlyJAhWCv3j9uUI6PPz1tVlm1Y+Hqr39UzxMZwJI/a87maj53',
  'gf8ri85GcnDIkKXVUNviKECUiUn4P4lyXpN/ccx6ZoB7m1q78l+vVQemjwnJwH9obHhpwG0V8ivAfpzgk39Sw44ddXnOStV/aXXOhj0YK69PAHpsjKk/XUR9',
  'F0B6NczHv2kbVXdXMMg9Ojlzd+6fP3t6RyNsfeex52J5SamPf1hzQGD1a2mLsD9x2DYQAIkiUMc/Wr76cJlRdK01QIHDcZq/Yeo0IMCDLJ/d/2K9s48/MTpH',
  'VQBlxmys/1WNDBlAkxSdzLdyEsmBvzftw0JAdCOJo3tXRQQnwJFsKffUgHKtkX95wqlmAINjH7dpW787Db+WmQTEv2GxEWoAWQzvMiSHai6ZR1Cd0R9Ai60H',
  '2FNouneMvyD6eFRAeAlTqxhM+s0XQI8Kosk/brORfr88arQ+QHiQDZ+/aTk3JdKNbYPxBHlBFI9/asBIZMB49tSxP2hdWhBjdXZbxz9xlGR3AEbV6jWAc0Nd',
  'mv9zr/4iSI5SBeD8c+qSj39Gk95dz1zBDK//Xcc3GgCJJxLTf2wNxoH/IDmrSVh0XWuoP1RNVijAi7fr+P+ReUWTf2ehZmaAcMZ2vi9lJbcGwJHzIcAha9wU',
  'aUBpdycpPHv465N/VzGhHGV9gR7VP25oG4RRFoF7TcB8fOiov2ILYhaEdifnx79u0Wh3ADYHtjkAcAq3nvF/GhIiwIJeLuVeeqGJj39UAHJfQGm2Ia//bK7v',
  'D76NbTDHP1WD522BUedrNUCGghWav13laiDAhsYv27FgOauO/yxlwlSAanWJrPhZgjYYg48338t/cxLAgb881TdCAHkG6aFvWCvdJ4CK6632OH8aD4//euQC',
  'ZYCHAK21f12QSQtplpk3xL9l4QtqAF2k0S8QhiYpl6FNqRofQIbRzNc/ZEgdi78d4GdSe3lJUan/UJFYF0CJr/rJP2oTVH0lOY0lPkBztfSfv272hiUAi5rV',
  '7mF6ZJmPf2ZJdmPWdBOSsP9reycQQHkR5Mc/bKJidsBL5tU1QHcpLJq/b3FuIkCJyLje/3JXMo9/QcwTWsBfFLuv/1jKmhoAjVBv0VRpUveB/yWrFEfAcqE/',
  'qD5QHIwoQJC6A/jejW2Zk39sWBdmgHWib7y/YosLCECTDXvBOWSzg2nAZrxZLACEkhqTf00t+h8AfIZ81b9lbRaImRjMMFBAd/arqT9YiHsXQH8oZMg/ZPGP',
  'eTMzBeg7gG/XWJ8/d7XXJMCAhu/qLXfxyI9/XKqJYuRrNxqwmHW0YhAAhCgKxz9gSrZzM1F0BDVAfbSbmr9nP5MiQICDvt3/aSQ7jz82z8RW6GSzRa6nUedg',
  'GcCWYgPN/26mroH/Mh+EQyBwyMSjh1OjmyfAlMRc+D+EQcWTf3cQuGYAfzs+ua9diYcOgJKalsS/XIOxakBUhDMzT4z6JZp/VB44H8COgJfYf2QuTI1/I7mj',
  'VEB0K7CsP1EkQheAlE4nyT91F++Atj3DRz58fbtDn79jqkomAIhzQfLFeUm7j39wlclkwH4S17ITZJDEEpl0/TvHP3WsGHcAQbF5NkBwSR2b5Hhk1iLAi3Fh',
  '4j923myPf0u5ll9AYELxr/9i00waAIUKc9P/bvwOgj8c4ldLHXV2O6g/WanRKMCGOkn4/5ZCsZN/YdZXZoBsZGq+f2j/UgbAlMAHvy5tUi9oZWfVLCjAfb6x',
  'k39ZoI8av31SqdU/cI3hg3cV/SVNAHpV4Ki/YEJMFU50XR3Hv3DIqXcAOa7KOQBtxFyef31seCLAhOG25Jl7+H6Pf1IGS19AaCEGr/9p1EEO14z6mcWgVJZ2',
  'bH5SWQk1AIjq8Jq/XBhkIMCJkFbaMGA55o6/KnslVEBsrgKsP1i8khhAkj/Ny2R1tK6Bfz7ZSUEJeqHpoH9aAtYngIj5cvV/fZl4j/938p9kwIayMrV/X8It',
  'Cn2WmSbEMmbvZmoAYBqPLiiG4EqWrUyIoh9AgziE1z9iTn2K4xxxA1E+eNScqf9T73QXQIcMjck/aIpMfKY3f5Y9rnGNOJ+/coeBJQCJCiftJXuGOY9/Y321',
  'Y0ByVc+w/24KHhBAfAigxz9pIvJ2wE33JDVAeL9dmr9tFxUiQIfgEt5/cKl9jz9ADs5aQGEIwa9/V2vAGcCPzUnP82mfS4H/KFIYR3Nxlx6nAk+qaShAkqST',
  '+D+MNvOTf28tNGaAePcEvLFgqw0IQJEMjMB/ZmZsacBp7e8rzoHKtZN/T8ZIHmp6eoDVv2cTiodoGCsST6Z5BHqpP1tYvBdAfXhEx79m+894KzGICDq3cUqJ',
  'nz95ulIksX3DWOiVeDzNj39afJ1iEWr3aLA/c8ADEACF41fHP13N4HIhUXSYNUB/1liav2Sc9iEhgHKn3f9l0+SPPzM1bVX3ZSUerSFTA+YZQJVhIs2/caOy',
  'gf804/FCQHHcrKN/VXstJ8CS4x34CYI8xJKQeGRzZgCBUjS4v1ykxA6AlNWwxL9fYiNqQFdbbzLAinHAmg1SWWkfQI4kXdh/Z04UjSMiQzNUQHYmGaw/TlmH',
  'F4CReqTJP3Gf3X+zPN4+PkB7Dtefv2Xr5CYAixPj8bh41jSPf20/eGTAe168sb9mxq4R0XTPKcc/c+VvdwBD9sY1wHHDr5s/dsQVIsCNcjbh/3UsIo9/SYty',
  'XsBenauv/2BNtRoAhx69079tkQaCPx6cgUo5dM9jqD9WsdQowIixy/j/lDuQk39k2mBmgG50m75/ZsoyBsCPk4LAP2nOkmlAa53ZKzR748+Tf1TNqRziexOX',
  '1T9rtSuFGRfmX08AfPOpqT9g8+8XQHeUrse/a+N3dwAyVc85gHGELZ8/feE5IwB/6MfmDHlJlI9/VjICX1Vr3M6wP2/MoxAAjAO5xz9X2DhvF1HnKjVAg8bJ',
  'mr9foWYgwIU4Ud0iYZEpjz8vaaJUgGd2TKz/V43TGUCQMXTLgXBVSIG/OsV5QgB1vG+iqlgrMyfAjiXR90d/KZ6Q1XtfIGXAhGUXtkZcmRwMfZaZeMS/ZAQY',
  'agBbVqEwtYXR15iMT01HH0CJLWbXP2dn+ow/HvokU9x5SbCqP06V4RdAi/cHyT9ssVl+Czq1qD5Advo2n79ryP0lIo7EhvAtei6Oj39oeNlkwHXj8bD/adZb',
  'EEB2yCrHP29nYHbASXKvNYB1ADSav3HykSJAjFLT3+Vzu7qPf0N1J1vfXKTgr/9btvcaAIq+FNKEao1sgf8jcu9ILHRd0qg/UlaFKECOpaL4/4+O2JN/ag4z',
  'ZoBz2ZS88mQoBAhAldnNwl5kd5FpwGUmMCxAhvpPlDVLMFQfQH8IVdXbY80UiVQZp6dQQHX+mKlpVtNJF0CBMJrJCmPNoHqENNfaPAFuGWiff3XBWSTAg3ns',
  '67x4ZAKPf14mB2NAbS+usL9z4cMQAIHU2Mc/ZCvHdNNRAYI1QHwbMZq/aPE+IkCDdCHd/2wG848/OgD1WDBks/Cvf1K0QBnAlB4Lzf9riNCB/y729ESdcMiR',
  'pIRSWe4oIpaZzvg/ho2vk39zvA1mPH1Qpbr3XmAgDoCQ8yzEv1lOWmpAUx5lNDSNWICaf1ZP7iCnjPrI2H9h3V+N/yVr8VRAcc/wrD9TAHcXwZaZj8lWd3+H',
  'gL8/b5o/n32LZZ+/YBvDJsCHJZj0EnlrfI+IcpIOZMCA/jezq2PN4hNpdf+ix792+OJ3AD8wpjaObY36nWd4ZLwiwImDOeJ/ePoyj39Ow0JfQGNb5q//ZNoi',
  'GgCBbuLT/3FK+YI/GfZkTCl1tHKoP1yocijAgsbJk39fR8pnAGsGk75/aqgFBsCVk3++mW4ZyGf9Z9liKMB/K4eTf1rStRpAfnGT1T9yF6yCwBbT8kyReWiT',
  'qHBfxkQU/3TRZce/cjh2dwA7f9k4v20ymp5/e8D8IsCGO0vkAXuJa49/UUcdX0BnUimv/2hdxA7AjhAyxRBVCbdr2FJZpjUAiwj0mp1bTaEgwIp4IdlQYDl4',
  'jr8pK7tUQG2bIKw/Vzz2GECT+9DK63ZMRoF/P841QEB62ICgf1tyDCeAh5u19X98GcmPv3bK3WTAhaKLtX9hO/cJr5aZ5MOoZn24afphkbgt3YdoRpYWS8uL',
  'H0CB8WTXAmGRVoqYG+tsUQB3a/Kp/1UYVRdAhX7MyT9nimZ8NzcMED2AcGnen79zoAIlAIe3zuy/e1SXj39iKJRjQHDksrD/bx2wEEB9le3HP2eBT3bAT03w',
  'NUB5rnqav2w2XiJAhtKD3nNvcNePPz6SZlpAYqetr39V4q8ZwJDuts96aahygf8pqcpHCXE7lKacUBx4KECTr0/4P4qmgJN/cIjLZoB6XNi8UWBYBwhAj6OD',
  'wH9nPkxpwGtxXCvAgGKfk39RM+od7noPU9W/aFR3hvIYKwxPA3lJpKk/XGo2F0B8Cs3Hv2giVXfQMOUiOoByV7OfP3qLDCQYfVCu5+t41niPf1mGT2GVa0Qu',
  'sD9yvHYQAIdq+cc/XF1UcVdRdHk1QIDaQ5q/YuCEIMCBgPTd/2Q/eY8/Mko6VVJlJaWs/1SQkxlAlF6HzYZyko+BvzY7vUJAczBgo39WfDsnwJI0Ovf/gTtC',
  'kgB41qdmAIJ0hrgcW/KnDoCWfv7Ev2B5w2ozWCsjMsCIYvyZv1GDTR9AjM632H9oLh6M/yFhIVRAdxtqq+dNbdcXgJAGwck/b/hsf0k83hg+QHmMoZ+/aAXl',
  'JgCMnIHxWnjWL49/a/B5ZMB6MS6xf2e3chERdM/exz9ylJh3AEVbHjWOcpIVmv91ruIiwI4wH+GedJPRj39IL7VegF1i/6//XuqSGgCIYzjTv2zxGoIVH1Qf',
  'ScN0YxGoP1VgdCjAigyE+P+SvdaTf2ZHy2aAb8pNvnRmCkQGwJDrn8A/avyKaUBqTFcqSXuG+ZN/Vf9AHMB8gt7VP2z88IS+F0NhTm19w/2pI2J2khc/dpkR',
  'x79taNZ3ADQZ+DkucRtJnv9+PUYiwIEHtOV/eb1Hj39VWZBfQGqXRbA/biP3EACNLAXHP1b2hW5FUefdNUCFbMKav17EDyDAhgYB3GVhHvOPPy3N/FSAaPT6',
  'rP9YsDMZQI9HF8t/cXKNgb87zlpCAHdKzKIfWCsyJ4GMiOf2lH8aQZBPe4apZYCFT821410XUgvZlpkzxL9k+GVqAFyEPC++hdHsmAdOYKwfQIg9htc/ZWPK',
  'i9oen1hTIXlJlqn/T5YXF0CLQFPJP2tawn2OOklWPkB1nrqfv22IqyUAjWz17zZ6LuaPf2ckOGRydM+6sP9q1h8QQHfGCcc/bf7ndsBKsBM1gHYs3pq/cJet',
  'IkCLAGffSHMVJI9/QocLW0Bd8Pev/1n8lxoAi8q80hhqEWGB/yUIPkgAc06UqD9RQREoQI/RD/j/jiYnk39rJp1mgHTkBry/Y4WDCECULpfBumRAHWnAZec8',
  'LACGFPOTv0u8kh9Afavv1b9kjE2I6xkQIVBAdvJMqT9XokwXQIArSciGZDR5edY0Emw7wG8KtZ9xdplJJMCCAGPrIXfx449/XXkNY0Brzruwv3TsBhAAg1tn',
  'xz9iLPxz7lF08TVAfM8dmr9oJz0iQIJe0d3/akmcjz84WrxXYWSzP69oUeedGcCVQXXN/20LsoH/MN2zQ/9wyImj7lLsNyfAlel0+D+Fkg6Tf3Uq52YAfilb',
  'umJdyMkOgJGkUcS/Wsb9akBT0AUzx4z6ZZp/VPtSH8WM+t3Yf2Lglo2/JI0HVEBzEymsP1HtHReAlY+wyT92kSKAvz5wTz7/fcNyn79h+vsmH4ebUPOAeUmi',
  'j39x3R1kwH/HjLLJY826EwJ1RR3HP3bl8HcAQH1kNkBvOpCcvHhkaiLAip5j4j94D8ePf01m/l9AYextr/9j4WYaAION6dP/b8hxgj8bge1LhXW0eKg/W0yf',
  'KMCEwueTf2C0Y2bia9xBvn9p+TkGwJOJ7b9/bGv4aPBonugo7XzdC5N/WG1lG6J9junVP286F4PlFjErTYB7SYuov2EtWRXYdPmPx79vo1l3ADfKyDkAbskC',
  'nn9+3sQiwIOPneUbe4aJj39TCHtfQGkFK6//axqZD2yNSAfGVVSW0mzuUgaVNQCHEbuav1zXIiDAiC3i2xNfxpqOvytocFRAa37MrH9ZgjEYQJCX4ct/dJJo',
  'gX89qKVBvXozb6CtWL2fJ4CJwzr1v36Fyo//eXfYZOGHm6y1f17VkgsKlpk0xL9my5FqAF7sPS6shmdZl0RNAnMfQIT76Nc/Y2eDi0UdIJ5R2nlJmKn/UkP+',
  'F0CILYTJP2lTMHz9OGTiPilyILGfv3C4/yUAif6g7dN7YaCPf2TipmNZc6V8sP9sr+QQQHqvccc/ayC+dsBNDiU1QHf0GJq/bjyCIkCIjAzev3Gdo48/QVQ7',
  'Wmhf8W2vv1hASRnAjk3d0HtpNGiB/ycC3UfAccEMp5RPzm8oQJFjU/h/jSIXk39t3/dmgHdd97y/YamgCECSHjTAp2VRqmnAaCHQLACDGfiTf07FGh7Ae3r3',
  '1b9mFQGH+xiVjFAueNY2qT9Z6qUXQH41QMf/ZcCaeIoyM0w7NnBoip8/ePNVJMB+zHvpUnfxro9/W3BEYoxq9xGwP3TzohAAhNZQxz9fAx9yz1F0RDVAfvcr',
  'mr9mQSohwIAAN93/Z7bKjz801uZWc2Ulca3iUhvBGUCWk9zNv3ACzoH/MyxZQp9xOwejf1StKCfAk9cF+D+DED2TUXhkvGYAgD9fuUZdIhEOgJOQCcS/XgTU',
  'akBWDd4ywIxa/Jo/UybDH0yOxCrYf2Xc8o1/IoVoVEB1WxysP0/EyReAkvG/yT9zYI+Afzzfvj5AfK/Yn79kcComAImkefI8eNZxj39u1OpkwHzHQ7G/ZZ2J',
  'Ekl0zxTHP3TSUXcAQrxrNgBwtYSbcHd/qCLAjHGV4f92JrOPf0p1Wl8AXywCr/9hyKEaAIYgB9P/bilLgj8dtU1KuXU3SKg/WCZzKMCHc3r4/5UREpN/Y0ja',
  'ZoBtSi++f2fhfwcJjyZGwH9pRSlpQGzQIivAfMXkk39Tt2AdAHpBX9V1aveIhZkYK2pPAHuUg6k/Xrj5F0B4snfHv2pfzncAMOgJOcByftafP3y40iNAfvUi',
  '5qB5SVyPf1colWA3a3m9sD9w6hgQAIps2cc/WPmzb9JRxcI1QIKFApq/YMWGIMCEWA3dimIXlY8/MGcdVMBmgsms/1Y6PhlAkYTZzAJwzsGBvzl/tkJAdRM/',
  'oxNXlhMnwJAu5fevf40WkW17E59l64QHSbbGW7+zDTCWmbLEv2LQ0WoAWkEAMZCGYOOY1U/RIx9AinPM16hokWeMdiAoxlQAeH8XqoNNZxkXQI1SzMk/bZU7',
  'foA7LmQ+QHe4VJ+/aglyJcCOhqTwtXm7Mo9/abosZMB3cGuxH2kscxBAdhMlxz9wgDF2wEgWdTWAdDgRmr9yzCkiQI1+COB5c+pIj39ExepdFlyk8a//XQE0',
  'GgCJ21zTFWr3wYH/IaKiSNx0XWOoP1NiaijAjaf0+P+QySCTf2jSzGaAcmvSvXVks8UIh5aZIcLIZTUBacBjttYstocpcpSiSvMsH0CAIZfV/2NFZYnlGqyW',
  'ULB1tDqpv1ZvjRdAgnyfyT9k/sp6+jWqQDygbhlIn791NlQk5ITszOw7eUK5j39fICpjQG5lYrD/cpf8EACAPIvHP2XBjHWJUPCnNUB7dCqav2oPWCJAhDwz',
  '3iptM1OPPzv85VkDZLNBr39Tu60ZwJNGic5haroKgf8tS6ZFk3DI6KVGUdsEKECVfon4P4ghupN/cwJfZoB8lhi7dl7hwg6Aj6bWxL9XvfBqYlJZSTSsjW0F',
  'mn9YcvggwIviB9h/YRESjj8m4NRUQHATraw/VB9sGECWSHLJ9HcgRYDHQOWvQD59UJSfv14t+yblhgEq9MJ6NOiPv3NcnmTAgnbitHli870UF3X+pMe/dWZH',
  'dwA96aY3ZGzBlp3/eQ+3IsCIuUjiinnPhI9/T280X0BlLt+v/2WBBRpAgExo1C9zBeaCPxkCQEyAdlzSqD9eItYowIFBVZN/XYnSZ0BqLoG+f2tDEA==',
].join('')

function unpack(packed: string): SkylineGrains {
  const raw = atob(packed)
  const n = (raw.length / 5) | 0
  const x = new Float32Array(n)
  const y = new Float32Array(n)
  const b = new Float32Array(n)
  for (let i = 0; i < n; i++) {
    const o = i * 5
    x[i] = ((raw.charCodeAt(o) << 8) | raw.charCodeAt(o + 1)) / 65535
    y[i] = ((raw.charCodeAt(o + 2) << 8) | raw.charCodeAt(o + 3)) / 65535
    b[i] = raw.charCodeAt(o + 4) / 255
  }
  return { n, x, y, b }
}

export const OUTLINE_GRAINS = unpack(PACK)
